刚开始考虑的时候，我还在考虑做mapmatching, 之后再做station-based prediction。现在想想好像也完全没有什么必要去做这个，只要把到站的GPS记录标有到站的找出来，然后找距离最近的一个点，再计算时间。

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import KFold #cross_validation

from sklearn.linear_model import BayesianRidge, LinearRegression, ElasticNet  # 批量导入要实现的回归算法
from sklearn.svm import LinearSVR  # SVM中的回归算法
from sklearn.svm import SVR  # SVM中的回归算法
from sklearn.ensemble.gradient_boosting import GradientBoostingRegressor  # 集成算法
from sklearn.neighbors import KNeighborsRegressor #  knn
from sklearn.model_selection import cross_val_score  # 交叉检验
from sklearn.metrics import explained_variance_score, mean_absolute_error, mean_squared_error, r2_score  # 批量导入指标算法
from sklearn.model_selection import GridSearchCV 
import matplotlib.pyplot as plt  # 导入图形展示库
from sklearn.preprocessing import StandardScaler #引入标准化模块
import seaborn as sns
from sklearn.neural_network import MLPRegressor
from sklearn.utils.validation import check_array as check_arrays
from sklearn.model_selection import train_test_split

In [2]:
#read reconstructed longitude and latitude
re_Long = pd.read_csv('reconstructed_Longitude.csv',encoding='utf-8',header=None)
re_Lat = pd.read_csv('reconstructed_Lat.csv',encoding='utf-8',header=None)

In [3]:
# read original yet noise-filtered table
original_table = pd.read_csv('noise_filtered_Route11Bus51938440.csv',encoding='utf-8',header=None)

In [4]:
min_len = min([len(re_Long),len(re_Lat)])

In [5]:
# original table should start here, at (len(original_table) - min_len)
table_1 = original_table.iloc[(len(original_table) - min_len):,:]

In [6]:
# slice re_Long in order to get the same length as re_Lat
re_Long = re_Long.tail(min_len) # get the last min_len rows of re_Long

In [7]:
table_1.reset_index(drop=True,inplace=True)

In [8]:
table_1

,0,1,2,3,4,5,6
0,2017-05-21 08:30:55,119.96924399999999,31.824138,5,2.0,3.0,46.0
1,2017-05-21 08:30:55,119.96924399999999,31.824138,5,NaN,NaN,46.0
2,2017-05-21 08:31:04,119.96948300000001,31.824383,5,NaN,NaN,NaN
3,2017-05-21 08:31:14,119.96965,31.824572999999997,5,NaN,NaN,NaN
4,2017-05-21 08:31:24,119.97008400000001,31.825184999999998,5,NaN,NaN,NaN
5,2017-05-21 08:31:34,119.970583,31.825865000000004,5,NaN,NaN,NaN
6,2017-05-21 08:31:45,119.970983,31.826508,5,NaN,NaN,NaN
7,2017-05-21 08:31:55,119.971208,31.826868,5,NaN,NaN,NaN
8,2017-05-21 08:32:04,119.97124,31.826909000000004,5,NaN,NaN,NaN
9,2017-05-21 08:32:15,119.97124,31.826909000000004,5,NaN,NaN,NaN
10,2017-05-21 08:32:25,119.97124,31.826909000000004,5,NaN,NaN,NaN
11,2017-05-21 08:32:34,119.97124,31.826909000000004,5,NaN,NaN,NaN
12,2017-05-21 08:32:45,119.97124,31.826909000000004,5,NaN,NaN,NaN
13,2017-05-21 08:32:54,119.97124,31.826909000000004,5,NaN,NaN,NaN
14,2017-05-21 08:33:04,119.97124,31.826909000000004,5,NaN,NaN,NaN
15,2017-05-21 08:33:15,119.97124299999999,31.826915000000003,5,NaN,NaN,NaN
16,2017-05-21 08:33:25,119.971476,31.827315999999996,5,NaN,NaN,NaN
17,2017-05-21 08:33:25,119.971476,31.827315999999996,5,1.0,3.0,47.0
18,2017-05-21 08:33:35,119.97169,31.827684,5,NaN,NaN,NaN
19,2017-05-21 08:33:44,119.97174299999999,31.827789000000003,5,2.0,3.0,47.0
20,2017-05-21 08:33:45,119.97178000000001,31.827868,5,NaN,NaN,NaN
21,2017-05-21 08:33:56,119.97211499999999,31.828488,5,NaN,NaN,NaN
22,2017-05-21 08:34:07,119.97263799999999,31.829328999999998,5,NaN,NaN,NaN
23,2017-05-21 08:34:17,119.97310300000001,31.830092999999998,5,NaN,NaN,NaN
24,2017-05-21 08:34:23,119.973423,31.830583,5,1.0,3.0,48.0
25,2017-05-21 08:34:27,119.973583,31.830833000000002,5,NaN,NaN,NaN
26,2017-05-21 08:34:38,119.97368600000001,31.83098,5,NaN,NaN,NaN
27,2017-05-21 08:34:38,119.973701,31.831003000000003,5,2.0,3.0,48.0
28,2017-05-21 08:34:47,119.973906,31.831378000000004,5,NaN,NaN,NaN
29,2017-05-21 08:34:57,119.97416799999999,31.832081,5,NaN,NaN,NaN
...,...,...,...,...,...,...,...
96232,2017-06-19 09:34:33,119.962028,31.800099,4,1.0,3.0,14.0
96233,2017-06-19 09:42:31,119.962245,31.800056,4,NaN,NaN,NaN
96234,2017-06-19 09:42:38,119.962671,31.799955999999998,4,2.0,3.0,14.0
96235,2017-06-19 09:42:38,119.962671,31.799955999999998,4,NaN,NaN,14.0
96236,2017-06-19 09:42:41,119.96290400000001,31.799896,4,NaN,NaN,NaN
96237,2017-06-19 09:42:50,119.963728,31.799696,4,NaN,NaN,NaN
96238,2017-06-19 09:43:00,119.96476799999999,31.799459999999996,4,NaN,NaN,NaN
96239,2017-06-19 09:43:10,119.96555500000001,31.799278,4,NaN,NaN,NaN
96240,2017-06-19 09:43:20,119.965759,31.799222999999998,4,NaN,NaN,NaN
96241,2017-06-19 09:43:31,119.965759,31.799222999999998,4,NaN,NaN,NaN
96242,2017-06-19 09:43:40,119.965759,31.799222999999998,4,NaN,NaN,NaN
96243,2017-06-19 09:43:51,119.965759,31.799222999999998,4,NaN,NaN,NaN
96244,2017-06-19 09:44:01,119.965976,31.799188,4,NaN,NaN,NaN
96245,2017-06-19 09:44:13,119.96596799999999,31.799355,4,NaN,NaN,NaN
96246,2017-06-19 09:44:23,119.96580800000001,31.799348,4,NaN,NaN,NaN
96247,2017-06-19 09:44:33,119.96523799999999,31.799459999999996,4,NaN,NaN,NaN
96248,2017-06-19 09:44:42,119.964533,31.799626,4,NaN,NaN,NaN
96249,2017-06-19 09:44:52,119.963619,31.799856,4,NaN,NaN,NaN
96250,2017-06-19 09:45:02,119.96281100000002,31.800099,4,NaN,NaN,NaN
96251,2017-06-19 09:45:12,119.961931,31.800345,4,NaN,NaN,NaN
96252,2017-06-19 09:45:23,119.96113600000001,31.800556,4,NaN,NaN,NaN
96253,2017-06-19 09:45:34,119.96016399999999,31.800867999999998,4,NaN,NaN,NaN
96254,2017-06-19 09:45:46,119.95915500000001,31.801308000000002,4,NaN,NaN,NaN
96255,2017-06-19 09:45:56,119.958271,31.801775,4,NaN,NaN,NaN
96256,2017-06-19 09:46:05,119.957536,31.802175,4,NaN,NaN,NaN
96257,2017-06-19 09:46:16,119.95727,31.802671000000004,4,NaN,NaN,NaN
96258,2017-06-19 09:46:26,119.957374,31.803085999999997,4,NaN,NaN,NaN
96259,2017-06-19 09:46:36,119.957603,31.803846000000004,4,NaN,NaN,NaN
96260,2017-06-19 09:46:47,119.957743,31.804347999999997,4,NaN,NaN,NaN
96261,2017-06-19 09:46:56,119.95780500000001,31.80449,4,NaN,NaN,NaN

In [9]:
#由于后面要做判断必须要把这些放在一起，到时候筛选数据的时候后面的时间，站点类型等信息都能保留
# pd.DataFrame(np.hstack([re_Long,table_1]))

In [10]:
# pd.DataFrame(np.hstack([re_Long,table_1]))

In [11]:
# table_1[table_1.iloc[:,4]=='1.0'].to_csv('station_list_downstream.csv',index=False)
#再到csv文件里边手动删除多余记录

In [12]:
# table_1[table_1.iloc[:,4]=='1.0'].to_csv('station_list_upstream.csv',index=False)
#再到csv文件里边手动删除多余记录

In [13]:
# stop_index = table_1[table_1.iloc[:,4]=='1.0'].index.values

In [14]:
# np.array(re_Lat)[table_1[table_1.iloc[:,4]=='1.0'].index.values]

缺省怎么来做

In [15]:
#read reconstructed longitude and latitude
# station_list_upstream = pd.read_csv('station_list_upstream.csv',encoding='utf-8')
# station_list_downstream = pd.read_csv('station_list_downstream.csv',encoding='utf-8')

In [16]:
# station_list_downstream

In [17]:
_, table_1_split, _, _ = train_test_split(table_1,table_1.iloc[:,-1], test_size=19500, shuffle=False)

In [18]:
table_1_split_reindex = table_1_split.reset_index(drop=True)

In [19]:
table_1_split_reindex

,0,1,2,3,4,5,6
0,2017-06-13 07:24:54,119.97706799999999,31.842440000000003,4,1.0,3.0,3.0
1,2017-06-13 07:25:02,119.976828,31.842240999999998,4,NaN,NaN,NaN
2,2017-06-13 07:25:13,119.976673,31.842015000000004,4,NaN,NaN,NaN
3,2017-06-13 07:25:13,119.976673,31.842015000000004,4,2.0,3.0,3.0
4,2017-06-13 07:25:23,119.97631499999999,31.841356,4,NaN,NaN,NaN
5,2017-06-13 07:25:33,119.97606299999998,31.840618,4,NaN,NaN,NaN
6,2017-06-13 07:25:42,119.97587800000001,31.840021000000004,4,NaN,NaN,NaN
7,2017-06-13 07:25:52,119.9754,31.839605,4,NaN,NaN,NaN
8,2017-06-13 07:26:02,119.975214,31.839321,4,NaN,NaN,NaN
9,2017-06-13 07:26:12,119.97513799999999,31.839013,4,NaN,NaN,NaN
10,2017-06-13 07:26:22,119.975141,31.839015000000003,4,NaN,NaN,NaN
11,2017-06-13 07:26:32,119.975141,31.839015000000003,4,NaN,NaN,NaN
12,2017-06-13 07:26:43,119.97508,31.838684999999998,4,NaN,NaN,NaN
13,2017-06-13 07:26:53,119.974901,31.837944,4,NaN,NaN,NaN
14,2017-06-13 07:27:02,119.974728,31.837071,4,NaN,NaN,NaN
15,2017-06-13 07:27:06,119.97469,31.836823,4,1.0,3.0,4.0
16,2017-06-13 07:27:12,119.974651,31.836415000000002,4,NaN,NaN,NaN
17,2017-06-13 07:27:22,119.97464599999999,31.836335,4,NaN,NaN,NaN
18,2017-06-13 07:27:22,119.97464599999999,31.836335,4,2.0,3.0,4.0
19,2017-06-13 07:27:34,119.974515,31.835576,4,NaN,NaN,NaN
20,2017-06-13 07:27:44,119.974351,31.834628000000002,4,NaN,NaN,NaN
21,2017-06-13 07:27:55,119.97415500000001,31.833534000000004,4,NaN,NaN,NaN
22,2017-06-13 07:28:01,119.974056,31.832929999999998,4,1.0,3.0,5.0
23,2017-06-13 07:28:05,119.974019,31.832746000000004,4,NaN,NaN,NaN
24,2017-06-13 07:28:14,119.973983,31.83254,4,NaN,NaN,NaN
25,2017-06-13 07:28:25,119.973983,31.83254,4,NaN,NaN,NaN
26,2017-06-13 07:28:35,119.973978,31.832442999999998,4,NaN,NaN,NaN
27,2017-06-13 07:28:37,119.97395900000001,31.832313,4,2.0,3.0,5.0
28,2017-06-13 07:28:45,119.97384299999999,31.831913,4,NaN,NaN,NaN
29,2017-06-13 07:28:55,119.97368300000001,31.831488,4,NaN,NaN,NaN
...,...,...,...,...,...,...,...
19470,2017-06-19 09:34:33,119.962028,31.800099,4,1.0,3.0,14.0
19471,2017-06-19 09:42:31,119.962245,31.800056,4,NaN,NaN,NaN
19472,2017-06-19 09:42:38,119.962671,31.799955999999998,4,2.0,3.0,14.0
19473,2017-06-19 09:42:38,119.962671,31.799955999999998,4,NaN,NaN,14.0
19474,2017-06-19 09:42:41,119.96290400000001,31.799896,4,NaN,NaN,NaN
19475,2017-06-19 09:42:50,119.963728,31.799696,4,NaN,NaN,NaN
19476,2017-06-19 09:43:00,119.96476799999999,31.799459999999996,4,NaN,NaN,NaN
19477,2017-06-19 09:43:10,119.96555500000001,31.799278,4,NaN,NaN,NaN
19478,2017-06-19 09:43:20,119.965759,31.799222999999998,4,NaN,NaN,NaN
19479,2017-06-19 09:43:31,119.965759,31.799222999999998,4,NaN,NaN,NaN
19480,2017-06-19 09:43:40,119.965759,31.799222999999998,4,NaN,NaN,NaN
19481,2017-06-19 09:43:51,119.965759,31.799222999999998,4,NaN,NaN,NaN
19482,2017-06-19 09:44:01,119.965976,31.799188,4,NaN,NaN,NaN
19483,2017-06-19 09:44:13,119.96596799999999,31.799355,4,NaN,NaN,NaN
19484,2017-06-19 09:44:23,119.96580800000001,31.799348,4,NaN,NaN,NaN
19485,2017-06-19 09:44:33,119.96523799999999,31.799459999999996,4,NaN,NaN,NaN
19486,2017-06-19 09:44:42,119.964533,31.799626,4,NaN,NaN,NaN
19487,2017-06-19 09:44:52,119.963619,31.799856,4,NaN,NaN,NaN
19488,2017-06-19 09:45:02,119.96281100000002,31.800099,4,NaN,NaN,NaN
19489,2017-06-19 09:45:12,119.961931,31.800345,4,NaN,NaN,NaN
19490,2017-06-19 09:45:23,119.96113600000001,31.800556,4,NaN,NaN,NaN
19491,2017-06-19 09:45:34,119.96016399999999,31.800867999999998,4,NaN,NaN,NaN
19492,2017-06-19 09:45:46,119.95915500000001,31.801308000000002,4,NaN,NaN,NaN
19493,2017-06-19 09:45:56,119.958271,31.801775,4,NaN,NaN,NaN
19494,2017-06-19 09:46:05,119.957536,31.802175,4,NaN,NaN,NaN
19495,2017-06-19 09:46:16,119.95727,31.802671000000004,4,NaN,NaN,NaN
19496,2017-06-19 09:46:26,119.957374,31.803085999999997,4,NaN,NaN,NaN
19497,2017-06-19 09:46:36,119.957603,31.803846000000004,4,NaN,NaN,NaN
19498,2017-06-19 09:46:47,119.957743,31.804347999999997,4,NaN,NaN,NaN
19499,2017-06-19 09:46:56,119.95780500000001,31.80449,4,NaN,NaN,NaN

In [20]:
temp_table = table_1_split_reindex[table_1_split_reindex.iloc[:,4]=='1.0']

In [21]:
temp_table

,0,1,2,3,4,5,6
0,2017-06-13 07:24:54,119.97706799999999,31.842440000000003,4,1.0,3.0,3.0
15,2017-06-13 07:27:06,119.97469,31.836823,4,1.0,3.0,4.0
22,2017-06-13 07:28:01,119.974056,31.832929999999998,4,1.0,3.0,5.0
44,2017-06-13 07:31:24,119.97036000000001,31.825885999999997,4,1.0,3.0,6.0
63,2017-06-13 07:34:10,119.968248,31.823365000000003,4,1.0,3.0,7.0
72,2017-06-13 07:35:09,119.96665300000001,31.821106,4,1.0,3.0,8.0
90,2017-06-13 07:37:48,119.962476,31.815345,4,1.0,3.0,9.0
116,2017-06-13 07:41:48,119.95961799999999,31.810840999999996,4,1.0,3.0,10.0
121,2017-06-13 07:42:23,119.959139,31.809185,4,1.0,3.0,11.0
131,2017-06-13 07:43:41,119.957676,31.804698,4,1.0,3.0,12.0
145,2017-06-13 07:45:43,119.958615,31.801409999999997,4,1.0,3.0,13.0
157,2017-06-13 07:47:27,119.962065,31.800114,4,1.0,3.0,14.0
169,2017-06-13 07:49:00,119.96658300000001,31.798921000000004,4,1.0,3.0,15.0
198,2017-06-13 07:53:18,119.971915,31.794915999999997,4,1.0,3.0,16.0
215,2017-06-13 07:55:38,119.97500600000001,31.791109999999996,4,1.0,3.0,17.0
231,2017-06-13 07:57:53,119.97738000000001,31.78841,4,1.0,3.0,18.0
248,2017-06-13 08:00:20,119.979496,31.785275,4,1.0,3.0,19.0
255,2017-06-13 08:00:56,119.977731,31.784039,4,1.0,3.0,20.0
289,2017-06-13 08:06:10,119.972353,31.777140999999997,4,1.0,3.0,54.0
305,2017-06-13 08:08:35,119.972219,31.774563,4,1.0,3.0,55.0
328,2017-06-13 08:12:02,119.966935,31.775218,4,1.0,9.0,26.0
329,2017-06-13 08:12:40,119.96658799999999,31.77569,5,1.0,8.0,27.0
345,2017-06-13 08:15:06,119.97215800000001,31.774421000000004,5,1.0,3.0,56.0
361,2017-06-13 08:17:15,119.97236299999999,31.777438,5,1.0,3.0,57.0
380,2017-06-13 08:20:12,119.976735,31.783109999999997,5,1.0,3.0,33.0
401,2017-06-13 08:23:16,119.979743,31.785975,5,1.0,3.0,34.0
412,2017-06-13 08:24:30,119.977496,31.788508,5,1.0,3.0,35.0
426,2017-06-13 08:26:29,119.974145,31.792379999999998,5,1.0,3.0,36.0
455,2017-06-13 08:30:50,119.971398,31.795588000000002,5,1.0,3.0,37.0
469,2017-06-13 08:32:37,119.96803100000001,31.798754,5,1.0,3.0,38.0
...,...,...,...,...,...,...,...
19027,2017-06-19 08:18:52,119.971428,31.795603000000003,5,1.0,3.0,37.0
19042,2017-06-19 08:20:57,119.968033,31.798758000000003,5,1.0,3.0,38.0
19060,2017-06-19 08:23:38,119.963774,31.799834000000004,5,1.0,3.0,39.0
19075,2017-06-19 08:25:42,119.95923400000001,31.801322999999996,5,1.0,3.0,40.0
19096,2017-06-19 08:28:56,119.957398,31.803217999999998,5,1.0,3.0,41.0
19113,2017-06-19 08:31:17,119.95911799999999,31.808193,5,1.0,3.0,42.0
19133,2017-06-19 08:34:22,119.960305,31.812083,5,1.0,3.0,43.0
19151,2017-06-19 08:37:01,119.962025,31.814565,5,1.0,3.0,44.0
19166,2017-06-19 08:39:19,119.966273,31.820046,5,1.0,3.0,45.0
19189,2017-06-19 08:42:52,119.968896,31.823721000000003,5,1.0,3.0,46.0
19208,2017-06-19 08:45:31,119.97149399999999,31.827313,5,1.0,3.0,47.0
19217,2017-06-19 08:46:38,119.973453,31.830598,5,1.0,3.0,48.0
19227,2017-06-19 08:48:00,119.97491799999999,31.836401000000002,5,1.0,3.0,49.0
19248,2017-06-19 08:51:11,119.976308,31.841168,5,1.0,3.0,50.0
19267,2017-06-19 08:53:57,119.983426,31.846628999999997,5,1.0,3.0,51.0
19287,2017-06-19 08:56:58,119.98827800000001,31.848879999999998,5,1.0,7.0,52.0
19288,2017-06-19 08:58:10,119.98786100000001,31.849153,4,1.0,6.0,1.0
19301,2017-06-19 09:00:02,119.98333600000001,31.846836,4,1.0,3.0,2.0
19315,2017-06-19 09:01:58,119.977026,31.842438,4,1.0,3.0,3.0
19335,2017-06-19 09:05:04,119.97471100000001,31.836824,4,1.0,3.0,4.0
19343,2017-06-19 09:06:00,119.9741,31.832929999999998,4,1.0,3.0,5.0
19366,2017-06-19 09:09:30,119.97035100000001,31.825865999999998,4,1.0,3.0,6.0
19382,2017-06-19 09:11:54,119.96821299999999,31.823346,4,1.0,3.0,7.0
19390,2017-06-19 09:12:45,119.96667,31.82106,4,1.0,3.0,8.0
19413,2017-06-19 09:16:04,119.962443,31.815271000000003,4,1.0,3.0,9.0
19435,2017-06-19 09:19:22,119.959645,31.810801,4,1.0,3.0,10.0
19440,2017-06-19 09:19:56,119.95911000000001,31.809168,4,1.0,3.0,11.0
19450,2017-06-19 09:21:13,119.95766299999998,31.804681,4,1.0,3.0,12.0
19461,2017-06-19 09:22:40,119.95860800000001,31.801388,4,1.0,3.0,13.0
19470,2017-06-19 09:34:33,119.962028,31.800099,4,1.0,3.0,14.0

In [22]:
stop_index = table_1_split_reindex[table_1_split_reindex.iloc[:,4]=='1.0'].index.values

In [23]:
stop_index

array([    0,    15,    22, ..., 19450, 19461, 19470], dtype=int64)

In [24]:
def prediction_process(X,y,stop_index):
    # 训练回归模型
    X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=19500, shuffle=False)
    
    model_knn = KNeighborsRegressor()  # 建立贝叶斯岭回归模型对象

    model_names = ['KNN']  # 不同模型的名称列表
    model_dic = [model_knn]  # 不同回归模型对象的集合

    pre_y_list = []  # 各个回归模型预测的y值列表
    for model in model_dic:  # 读出每个回归模型对象
        pre_y_list.append(model.fit(X_train, y_train).predict(X_test[stop_index]))  # 将回归训练中得到的预测y存入列表，要分训练集和预测集
    # 模型效果指标评估

    
    return pre_y_list, y_test[stop_index]

In [ ]:
# def mae_DCE(iteration, re_Long):
    
#     mae_list = []
    
#     for i in range(iteration):

#         prediction_step = i+1
#         X_Long = np.array(re_Long.head(min_len-prediction_step))
#         y_Long = np.array(re_Long.iloc[:,-1].tail(min_len-prediction_step))
#         y_Long = y_Long.reshape([min_len-prediction_step,1])

#         pre_y_list, y_test = prediction_process(X_Long,y_Long)
        
#         test = abs(y_test-pre_y_list[0])
        
#         y_no_noise_loc = np.where(test < 0.1)[0]
#         y_test_filtered = y_test[y_no_noise_loc].reshape(-1,1)
#         y_pred_filtered = pre_y_list[0][y_no_noise_loc]
#         mae_list.append(mean_absolute_error(y_test_filtered,y_pred_filtered))
    
#     return mae_list

In [31]:
def DCE_predictor(iteration, re_Long, stop_index):
    for i in range(iteration):
        prediction_step = i+1
        X_Long = np.array(re_Long.head(min_len-prediction_step))
        y_Long = np.array(re_Long.iloc[:,-1].tail(min_len-prediction_step))
        y_Long = y_Long.reshape([min_len-prediction_step,1])

        pre_y_list, y_test = prediction_process(X_Long,y_Long,stop_index)

        test = abs(y_test-pre_y_list[0])

    #     y_no_noise_loc = np.where(test < 0.1)[0]
    #     y_test_filtered = y_test[y_no_noise_loc].reshape(-1,1)
    #     y_pred_filtered = pre_y_list[0][y_no_noise_loc]

        if i ==0:
            temp_test = pd.DataFrame(y_test)
            temp_pred = pd.DataFrame(pre_y_list[0])
        else:
            temp_test = pd.concat([temp_test,pd.DataFrame(y_test)], ignore_index=True, axis=1)
            temp_pred = pd.concat([temp_pred,pd.DataFrame(pre_y_list[0])], ignore_index=True, axis=1)
    
    return temp_test,temp_pred

In [28]:
iteration = 250
for i in range(iteration):

    prediction_step = i+1
    X_Long = np.array(re_Long.head(min_len-prediction_step))
    y_Long = np.array(re_Long.iloc[:,-1].tail(min_len-prediction_step))
    y_Long = y_Long.reshape([min_len-prediction_step,1])
    
    pre_y_list, y_test = prediction_process(X_Long,y_Long,stop_index)

    test = abs(y_test-pre_y_list[0])

#     y_no_noise_loc = np.where(test < 0.1)[0]
#     y_test_filtered = y_test[y_no_noise_loc].reshape(-1,1)
#     y_pred_filtered = pre_y_list[0][y_no_noise_loc]
    
    if i ==0:
        temp_test = pd.DataFrame(y_test)
        temp_pred = pd.DataFrame(pre_y_list[0])
    else:
        temp_test = pd.concat([temp_test,pd.DataFrame(y_test)], ignore_index=True, axis=1)
        temp_pred = pd.concat([temp_pred,pd.DataFrame(pre_y_list[0])], ignore_index=True, axis=1)

In [32]:
y_test_Long, y_predict_Long = DCE_predictor(250, re_Long, stop_index)

In [ ]:
pd.DataFrame(y_predict_Long)

In [ ]:
pd.DataFrame(y_test_Long)

In [34]:
y_test_Lat, y_predict_Lat = DCE_predictor(250, re_Lat, stop_index)

In [38]:
y_predict_Long

,0,1,2,3,4,5,6,7,8,9,...,240,241,242,243,244,245,246,247,248,249
0,119.978242,119.978283,119.979450,119.979450,119.979940,119.979016,119.979016,119.979016,119.979710,119.979710,...,119.979016,119.979016,119.979016,119.979016,119.980125,119.980125,119.980055,119.979016,119.979016,119.979016
1,119.976721,119.976410,119.976042,119.975970,119.975687,119.975461,119.975211,119.975211,119.972511,119.969757,...,119.982599,119.982622,119.983228,119.984075,119.984672,119.985750,119.987352,119.986150,119.985078,119.983970
2,119.975602,119.975508,119.974874,119.974781,119.974781,119.974781,119.975550,119.975736,119.975485,119.975229,...,119.982276,119.981974,119.981494,119.980114,119.980673,119.980132,119.979398,119.978636,119.979332,119.981525
3,119.970870,119.970870,119.969098,119.969475,119.970489,119.972513,119.974666,119.974697,119.976209,119.977291,...,119.974886,119.974974,119.974306,119.975161,119.974875,119.974790,119.974840,119.975180,119.975003,119.974955
4,119.968635,119.968518,119.967904,119.967776,119.967776,119.967641,119.970228,119.971699,119.970544,119.966325,...,119.974152,119.974143,119.972862,119.973442,119.972899,119.973391,119.973990,119.974039,119.974039,119.973990
5,119.967168,119.967974,119.966763,119.966424,119.966424,119.966334,119.966334,119.966424,119.966334,119.967030,...,119.974005,119.973874,119.973901,119.973860,119.973880,119.973856,119.973880,119.974036,119.973814,119.973973
6,119.963465,119.963401,119.963401,119.962988,119.962988,119.963701,119.963878,119.964676,119.964676,119.964674,...,119.967773,119.967773,119.968970,119.967830,119.970445,119.970249,119.972568,119.969894,119.968501,119.968501
7,119.959765,119.959765,119.959856,119.959765,119.959765,119.959765,119.959765,119.959656,119.959656,119.959564,...,119.966897,119.968633,119.968550,119.966778,119.965024,119.966426,119.967500,119.966386,119.964703,119.964559
8,119.959325,119.959367,119.959292,119.959425,119.959425,119.959332,119.959332,119.959425,119.959332,119.959332,...,119.965260,119.966190,119.964960,119.964115,119.965021,119.965995,119.967814,119.967799,119.966133,119.964416
9,119.958140,119.958532,119.958452,119.958646,119.958452,119.958214,119.958214,119.957805,119.957805,119.957956,...,119.962926,119.962924,119.962139,119.962139,119.961736,119.962701,119.961694,119.964660,119.964794,119.963343
10,119.957035,119.957036,119.957038,119.957038,119.957038,119.957036,119.957036,119.957036,119.957036,119.957036,...,119.959435,119.959945,119.959857,119.959615,119.959562,119.959820,119.959938,119.960022,119.962891,119.960718
11,119.960154,119.960154,119.960525,119.960525,119.959937,119.959949,119.959373,119.959373,119.959376,119.959715,...,119.957515,119.957550,119.957728,119.960337,119.962366,119.962163,119.963074,119.962789,119.962789,119.961845
12,119.965483,119.964829,119.963563,119.962698,119.962698,119.962999,119.963012,119.962698,119.963105,119.963563,...,119.960376,119.960297,119.959451,119.964425,119.957400,119.957305,119.959129,119.961541,119.961560,119.961555
13,119.971284,119.971365,119.971499,119.971499,119.971499,119.971365,119.971284,119.971284,119.971284,119.971284,...,119.962058,119.963577,119.963577,119.969423,119.966501,119.964597,119.960582,119.964907,119.962944,119.964859
14,119.973951,119.973937,119.973862,119.973874,119.973950,119.973937,119.973521,119.973536,119.973460,119.973937,...,119.970094,119.970192,119.970350,119.970373,119.970729,119.973679,119.973861,119.973554,119.973341,119.973341
15,119.977748,119.977748,119.977748,119.977740,119.977578,119.977578,119.977578,119.977662,119.977740,119.977748,...,119.962771,119.962868,119.964812,119.968428,119.971803,119.970016,119.967427,119.967539,119.970840,119.976787
16,119.979656,119.979656,119.979656,119.979674,119.979674,119.979674,119.979674,119.979674,119.979656,119.979656,...,119.979656,119.980673,119.981763,119.981900,119.982831,119.979591,119.974025,119.962646,119.962713,119.957488
17,119.978918,119.979334,119.979182,119.979182,119.979182,119.979039,119.979182,119.979182,119.979039,119.979039,...,119.977287,119.977824,119.978326,119.978148,119.977773,119.978951,119.979182,119.979182,119.980597,119.982522
18,119.972897,119.972454,119.972010,119.971987,119.972578,119.972147,119.972213,119.972058,119.972351,119.972847,...,119.975065,119.972674,119.972674,119.972674,119.972674,119.972847,119.972847,119.975833,119.978792,119.978209
19,119.970273,119.970948,119.971066,119.971066,119.970841,119.970841,119.970588,119.970805,119.970273,119.970273,...,119.971523,119.971306,119.971259,119.971037,119.971306,119.971066,119.971066,119.970841,119.975309,119.977591
20,119.967873,119.968286,119.968919,119.969104,119.970197,119.971209,119.971101,119.970598,119.969939,119.969417,...,119.968662,119.969104,119.969104,119.968473,119.967860,119.966794,119.966561,119.966629,119.966900,119.966629
21,119.968130,119.968384,119.968697,119.969390,119.969535,119.970557,119.971463,119.971292,119.970717,119.969994,...,119.969104,119.969104,119.969535,119.969535,119.968650,119.967913,119.966680,119.966502,119.966900,119.967284
22,119.973288,119.973364,119.973474,119.973202,119.973251,119.973213,119.972895,119.972742,119.972664,119.972664,...,119.973402,119.973402,119.973402,119.973270,119.971472,119.971511,119.971511,119.970546,119.972476,119.973270
23,119.972929,119.973245,119.973340,119.973046,119.973224,119.972988,119.973175,119.973497,119.972754,119.971770,...,119.972055,119.972999,119.971928,119.971648,119.971648,119.971623,119.971623,119.971648,119.971623,119.971623
24,119.976767,119.976921,119.976704,119.975962,119.975505,119.975505,119.975580,119.976451,119.976761,119.976761,...,119.978932,119.978932,119.978853,119.978932,119.978932,119.978932,119.979296,119.978932,119.978129,119.977907
25,119.979120,119.978387,119.977276,119.977011,119.976854,119.976454,119.976210,119.975908,119.976503,119.977858,...,119.976915,119.976729,119.976729,119.976729,119.976729,119.976729,119.976473,119.976473,119.973318,119.973318
26,119.977690,119.977966,119.978159,119.977842,119.977698,119.978154,119.978037,119.978203,119.978216,119.977888,...,119.974053,119.974053,119.973904,119.973904,119.974053,119.974464,119.974764,119.974764,119.974629,119.974663
27,119.974188,119.974154,119.974405,119.975037,119.975577,119.975745,119.975504,119.975504,119.975504,119.975504,...,119.972105,119.972105,119.972105,119.972084,119.972084,119.972084,119.972084,119.972254,119.972142,119.972142
28,119.971827,119.971975,119.971909,119.971985,119.971985,119.972133,119.972128,119.972138,119.971928,119.971658,...,119.967613,119.967848,119.967942,119.967961,119.967798,119.967848,119.967616,119.967632,119.967800,119.967848
29,119.967672,119.967672,119.967672,119.967672,119.967672,119.967425,119.967425,119.967425,119.968117,119.968417,...,119.961992,119.962323,119.962799,119.962799,119.962799,119.962579,119.962323,119.961992,119.961600,119.961600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1226,119.968115,119.967839,119.967611,119.967275,119.966770,119.966097,119.965358,119.964583,119.963970,119.963572,...,119.965494,119.966555,119.967582,119.967582,119.967148,119.966602,119.966816,119.966884,119.966110,119.965327
1227,119.967275,119.967275,119.966770,119.966331,119.965795,119.966018,119.965276,119.964583,119.963970,119.963572,...,119.961370,119.961266,119.961622,119.961226,119.961226,119.961226,119.961171,119.961422,119.961726,119.964798
1228,119.958908,119.959704,119.959747,119.961463,119.961577,119.961811,119.961718,119.961630,119.961635,119.961680,...,119.963600,119.963995,119.964291,119.964472,119.964542,119.964542,119.964546,119.964546,119.964678,119.965156
1229,119.959816,119.959917,119.960016,119.960099,119.960208,119.960325,119.960411,119.960469,119.960610,119.960817,...,119.974863,119.972663,119.972663,119.972746,119.972801,119.970641,119.972844,119.974583,119.974353,119.974137
1230,119.960080,119.960047,119.960092,119.960162,119.960254,119.960357,119.960432,119.960552,119.960703,119.960828,...,119.974964,119.974964,119.974964,119.974995,119.975035,119.974398,119.973386,119.972859,119.972176,119.972176
1231,119.963254,119.961915,119.960630,119.961568,119.963194,119.963002,119.961957,119.960458,119.959414,119.960069,...,119.973300,119.972082,119.971371,119.971499,119.972202,119.972278,119.972348,119.972353,119.972376,119.972529
1232,119.966586,119.966656,119.966775,119.966952,119.967217,119.967537,119.967931,119.968274,119.968113,119.967636,...,119.986986,119.986797,119.986281,119.986278,119.986892,119.986905,119.986515,119.985911,119.985900,119.986112
1233,119.967217,119.967217,119.967537,119.967931,119.968274,119.968646,119.968646,119.968926,119.969138,119.969258,...,119.985164,119.984911,119.984705,119.984585,119.984640,119.984640,119.985180,119.986261,119.986521,119.986645
1234,119.969517,119.969637,119.970573,119.970573,119.970336,119.969778,119.969481,119.969446,119.969234,119.968858,...,119.983396,119.983566,119.983566,119.983811,119.983811,119.977154,119.975614,119.977433,119.977570,119.980288
1235,119.973618,119.973741,119.973901,119.974057,119.974246,119.974455,119.974455,119.974621,119.974741,119.974741,...,119.983951,119.984201,119.984460,119.984375,119.984750,119.985167,119.985167,119.985628,119.986101,119.986604
1236,119.975028,119.975009,119.975017,119.974998,119.975167,119.975084,119.974905,119.974741,119.974825,119.974871,...,119.982959,119.982733,119.982435,119.981935,119.981230,119.980306,119.980331,119.979644,119.979016,119.979447
1237,119.974960,119.975009,119.975125,119.975207,119.975390,119.975833,119.976082,119.976082,119.976304,119.976437,...,119.982733,119.982435,119.981935,119.981230,119.981230,119.980306,119.979286,119.978412,119.977702,119.977167
1238,119.975876,119.976060,119.976195,119.976462,119.976261,119.976227,119.976304,119.976007,119.976146,119.976026,...,119.976545,119.976788,119.978977,119.979505,119.980057,119.979286,119.978412,119.977702,119.977167,119.976860
1239,119.976547,119.976703,119.976654,119.976814,119.977091,119.977572,119.978205,119.979026,119.979026,119.979986,...,119.976353,119.976167,119.975982,119.975796,119.975764,119.975764,119.975764,119.975764,119.975738,119.975633
1240,119.982733,119.982435,119.981935,119.981230,119.980306,119.979286,119.977702,119.977167,119.976860,119.976679,...,119.975008,119.974940,119.974870,119.974795,119.974723,119.974685,119.974663,119.974618,119.974545,119.974440
1241,119.982467,119.982159,119.982159,119.981851,119.981522,119.981181,119.980796,119.980259,119.979561,119.978751,...,119.973620,119.974238,119.974238,119.974663,119.974618,119.974545,119.974545,119.974440,119.974390,119.974291
1242,119.982467,119.982159,119.981851,119.981851,119.981522,119.981181,119.980796,119.980259,119.979561,119.978751,...,119.973620,119.973716,119.974238,119.974218,119.974618,119.974545,119.974440,119.974440,119.974321,119.974291
1243,119.982343,119.982650,119.982059,119.981688,119.980843,119.980647,119.978751,119.978062,119.977499,119.977134,...,119.969805,119.969751,119.971657,119.971634,119.971909,119.972002,119.971648,119.971440,119.971285,119.971193
1244,119.977067,119.976847,119.976847,119.976847,119.976847,119.976702,119.976574,119.976957,119.979332,119.979526,...,119.968913,119.968900,119.968900,119.968898,119.968823,119.968697,119.968540,119.968335,119.968104,119.967935
1245,119.973926,119.973914,119.973906,119.973901,119.973898,119.973898,119.973885,119.973817,119.974053,119.974286,...,119.968913,119.968898,119.968823,119.968699,119.968617,119.968665,119.968493,119.968307,119.968093,119.967897
1246,119.974217,119.974057,119.974046,119.974022,119.973898,119.973885,119.973885,119.973817,119.973658,119.973401,...,119.972413,119.973001,119.970613,119.970378,119.970174,119.970148,119.970031,119.967940,119.968016,119.967825
1247,119.971654,119.971654,119.971447,119.971189,119.971189,119.971447,119.971447,119.971189,119.971189,119.970932,...,119.960237,119.962835,119.968265,119.968205,119.968086,119.967896,119.965179,119.964987,119.964835,119.960224
1248,119.966855,119.966750,119.966595,119.966578,119.966544,119.966066,119.965835,119.966652,119.968409,119.968188,...,119.960002,119.960002,119.959989,119.959989,119.959989,119.959989,119.959989,119.959392,119.959392,119.959912
1249,119.967937,119.967830,119.967650,119.967608,119.967221,119.966817,119.966354,119.965773,119.965520,119.965363,...,119.959989,119.959989,119.959989,119.959989,119.959989,119.959989,119.959970,119.959912,119.959832,119.959832
1250,119.964797,119.964797,119.964797,119.964797,119.964797,119.964637,119.964388,119.964388,119.964713,119.965686,...,119.957381,119.957300,119.957220,119.957220,119.957147,119.957173,119.958182,119.958868,119.958757,119.961010
1251,119.959541,119.959222,119.958439,119.958760,119.958690,119.958613,119.958562,119.958268,119.958001,119.957889,...,119.957147,119.957100,119.957059,119.957093,119.957293,119.957601,119.957958,119.958368,119.958735,119.958942
1252,119.959861,119.959749,119.959652,119.959518,119.959357,119.959136,119.958745,119.958032,119.958423,119.958308,...,119.957147,119.957100,119.957059,119.957093,119.957293,119.957601,119.957958,119.958368,119.958735,119.958942
1253,119.959426,119.959523,119.959426,119.959426,119.959426,119.959345,119.959345,119.959244,119.959244,119.959143,...,119.972660,119.972898,119.973150,119.973101,119.973109,119.972983,119.962718,119.962062,119.960529,119.958942
1254,119.957802,119.956963,119.956963,119.956963,119.957116,119.957116,119.957450,119.957450,119.958584,119.958500,...,119.973150,119.972825,119.973077,119.973060,119.973384,119.973541,119.973903,119.973963,119.974083,119.974523
1255,119.961150,119.960201,119.959760,119.960174,119.960174,119.960498,119.960035,119.959806,119.957341,119.958108,...,119.967878,119.968230,119.968634,119.968605,119.969111,119.969618,119.972476,119.974942,119.974759,119.974811

In [80]:
y_predict_Lat.iloc[4]

0      31.823856
1      31.823856
2      31.823856
3      31.823607
4      31.823326
5      31.823101
6      31.823101
7      31.822904
8      31.822904
9      31.822725
10     31.822725
11     31.822534
12     31.822725
13     31.822725
14     31.822831
15     31.823101
16     31.822904
17     31.822725
18     31.822725
19     31.822725
20     31.822725
21     31.822890
22     31.822904
23     31.822904
24     31.822725
25     31.822534
26     31.822534
27     31.822263
28     31.822368
29     31.823101
         ...
220    31.832627
221    31.833567
222    31.835375
223    31.835236
224    31.834975
225    31.836576
226    31.838274
227    31.836264
228    31.831718
229    31.832029
230    31.835328
231    31.836922
232    31.840109
233    31.840109
234    31.840109
235    31.840109
236    31.840109
237    31.840116
238    31.840178
239    31.840116
240    31.840116
241    31.840109
242    31.840109
243    31.840109
244    31.840109
245    31.840109
246    31.840109
247    31.840109
248    31.840109
249    31.840109
Name: 4, Length: 250, dtype: float64

In [81]:
y_predict_Long.iloc[4]

0      119.968635
1      119.968518
2      119.967904
3      119.967776
4      119.967776
5      119.967641
6      119.970228
7      119.971699
8      119.970544
9      119.966325
10     119.966439
11     119.964967
12     119.964925
13     119.965173
14     119.964056
15     119.967904
16     119.967904
17     119.967904
18     119.967904
19     119.967776
20     119.967776
21     119.963660
22     119.961931
23     119.961103
24     119.961472
25     119.961806
26     119.961100
27     119.961374
28     119.961903
29     119.963853
          ...
220    119.972872
221    119.972131
222    119.972131
223    119.972330
224    119.973850
225    119.973850
226    119.970605
227    119.970357
228    119.973582
229    119.974706
230    119.974015
231    119.974542
232    119.974356
233    119.974457
234    119.974303
235    119.974123
236    119.974045
237    119.974039
238    119.974181
239    119.973964
240    119.974152
241    119.974143
242    119.972862
243    119.973442
244    119.972899
245    119.973391
246    119.973990
247    119.974039
248    119.974039
249    119.973990
Name: 4, Length: 250, dtype: float64

In [91]:
aaa = np.c_[np.array(y_predict_Lat.iloc[4]),np.array(y_predict_Long.iloc[4])]

In [92]:
aaa

array([[ 31.8238558, 119.9686352],
       [ 31.8238558, 119.9685182],
       [ 31.8238558, 119.9679038],
       [ 31.8236074, 119.9677762],
       [ 31.8233262, 119.9677762],
       [ 31.8231006, 119.9676406],
       [ 31.8231006, 119.9702282],
       [ 31.8229036, 119.9716992],
       [ 31.8229036, 119.970544 ],
       [ 31.8227254, 119.9663248],
       [ 31.8227254, 119.9664392],
       [ 31.8225336, 119.9649666],
       [ 31.8227254, 119.9649248],
       [ 31.8227254, 119.9651728],
       [ 31.8228306, 119.9640562],
       [ 31.8231006, 119.9679038],
       [ 31.8229036, 119.9679038],
       [ 31.8227254, 119.9679038],
       [ 31.8227254, 119.9679038],
       [ 31.8227254, 119.9677762],
       [ 31.8227254, 119.9677762],
       [ 31.82289  , 119.9636604],
       [ 31.8229036, 119.961931 ],
       [ 31.8229036, 119.961103 ],
       [ 31.8227254, 119.9614718],
       [ 31.8225336, 119.9618056],
       [ 31.8225336, 119.9611004],
       [ 31.8222628, 119.9613738],
       [ 31.822368 , 119.9619034],
       [ 31.8231006, 119.9638534],
       [ 31.8231006, 119.9655374],
       [ 31.8229036, 119.968658 ],
       [ 31.8229036, 119.9689948],
       [ 31.8227254, 119.9695198],
       [ 31.8227254, 119.9695198],
       [ 31.8227978, 119.9701096],
       [ 31.8225664, 119.969325 ],
       [ 31.8225664, 119.9698994],
       [ 31.8223222, 119.9702606],
       [ 31.8223358, 119.9721366],
       [ 31.8223462, 119.9725846],
       [ 31.8225336, 119.972396 ],
       [ 31.8222628, 119.9721014],
       [ 31.8222628, 119.9680454],
       [ 31.8225336, 119.9679038],
       [ 31.8225336, 119.9679038],
       [ 31.8225336, 119.9679038],
       [ 31.8225336, 119.9701096],
       [ 31.8231156, 119.970724 ],
       [ 31.8243226, 119.9699524],
       [ 31.8240428, 119.9692496],
       [ 31.8233262, 119.9692096],
       [ 31.8231006, 119.969013 ],
       [ 31.8229036, 119.96889  ],
       [ 31.8229036, 119.9676406],
       [ 31.8229036, 119.9676406],
       [ 31.8227254, 119.965884 ],
       [ 31.8227254, 119.9644682],
       [ 31.8188672, 119.9646042],
       [ 31.8237272, 119.9624498],
       [ 31.8246322, 119.9642284],
       [ 31.8242618, 119.9690714],
       [ 31.8231482, 119.9783202],
       [ 31.8236566, 119.9785346],
       [ 31.823679 , 119.9829416],
       [ 31.8263248, 119.971972 ],
       [ 31.8256028, 119.9734136],
       [ 31.8253178, 119.9744194],
       [ 31.827293 , 119.9745784],
       [ 31.827023 , 119.9742192],
       [ 31.8280206, 119.97482  ],
       [ 31.8293642, 119.9748642],
       [ 31.831457 , 119.9750052],
       [ 31.831457 , 119.975    ],
       [ 31.8324902, 119.974811 ],
       [ 31.8295482, 119.974684 ],
       [ 31.8309036, 119.9745958],
       [ 31.8298246, 119.9745892],
       [ 31.829958 , 119.9731132],
       [ 31.8291626, 119.9730372],
       [ 31.8291626, 119.9708362],
       [ 31.8291626, 119.97067  ],
       [ 31.8293932, 119.9724154],
       [ 31.8308852, 119.971493 ],
       [ 31.8319882, 119.9724434],
       [ 31.8332588, 119.972365 ],
       [ 31.8338088, 119.968335 ],
       [ 31.834946 , 119.9745312],
       [ 31.8345248, 119.974411 ],
       [ 31.834507 , 119.9743932],
       [ 31.8343506, 119.9743834],
       [ 31.83363  , 119.974361 ],
       [ 31.8332588, 119.973007 ],
       [ 31.8332588, 119.9680454],
       [ 31.8319882, 119.9679038],
       [ 31.830497 , 119.9702764],
       [ 31.832939 , 119.9718872],
       [ 31.834637 , 119.9718872],
       [ 31.835251 , 119.9715806],
       [ 31.8348206, 119.9715806],
       [ 31.8352194, 119.972522 ],
       [ 31.834507 , 119.9729898],
       [ 31.833733 , 119.9735086],
       [ 31.8338704, 119.9735086],
       [ 31.8332214, 119.9732008],
       [ 31.8327788, 119.9739664],
       [ 31.8323886, 119.9735064],
       [ 31.8321316, 119.9735064],
       [ 31.832183 , 119.9696294],
       [ 31.832183 , 119.9706008],
       [ 31.832183 , 119.9716238],
       [ 31.832183 , 119.9739866],
       [ 31.8321316, 119.9714724],
       [ 31.8294242, 119.9742044],
       [ 31.8290642, 119.973687 ],
       [ 31.829082 , 119.9733798],
       [ 31.8298906, 119.9736114],
       [ 31.827652 , 119.9739316],
       [ 31.8280206, 119.9739044],
       [ 31.8291626, 119.9743372],
       [ 31.8293932, 119.97431  ],
       [ 31.8289136, 119.9746926],
       [ 31.8292646, 119.9749226],
       [ 31.8291312, 119.974272 ],
       [ 31.8288946, 119.973531 ],
       [ 31.8310628, 119.9726492],
       [ 31.8328172, 119.97385  ],
       [ 31.8344302, 119.9733254],
       [ 31.832908 , 119.9717376],
       [ 31.832529 , 119.972684 ],
       [ 31.8334854, 119.9738202],
       [ 31.833481 , 119.9746614],
       [ 31.832529 , 119.9743076],
       [ 31.8328574, 119.9737888],
       [ 31.8332588, 119.9718986],
       [ 31.8327246, 119.9715952],
       [ 31.8324606, 119.9719618],
       [ 31.832497 , 119.9707468],
       [ 31.832529 , 119.974411 ],
       [ 31.8324006, 119.9743982],
       [ 31.8324006, 119.9734384],
       [ 31.8328068, 119.9694084],
       [ 31.8337676, 119.9693074],
       [ 31.8336662, 119.9692998],
       [ 31.832817 , 119.9697292],
       [ 31.832645 , 119.9672218],
       [ 31.832529 , 119.9696812],
       [ 31.832529 , 119.9726026],
       [ 31.8324006, 119.9728994],
       [ 31.8322338, 119.974323 ],
       [ 31.832605 , 119.974783 ],
       [ 31.8329438, 119.974783 ],
       [ 31.833106 , 119.975    ],
       [ 31.8325624, 119.975    ],
       [ 31.8325424, 119.975    ],
       [ 31.8324744, 119.97477  ],
       [ 31.834725 , 119.9741046],
       [ 31.834725 , 119.9721198],
       [ 31.8345046, 119.9729082],
       [ 31.8341376, 119.9741456],
       [ 31.835277 , 119.9739866],
       [ 31.8361312, 119.9739074],
       [ 31.8361312, 119.9741142],
       [ 31.8355832, 119.9743764],
       [ 31.8352406, 119.9743464],
       [ 31.8361888, 119.9743046],
       [ 31.8373188, 119.974699 ],
       [ 31.8323748, 119.9742188],
       [ 31.8322292, 119.97454  ],
       [ 31.8325728, 119.97431  ],
       [ 31.8334382, 119.974154 ],
       [ 31.8334842, 119.974135 ],
       [ 31.8334842, 119.9741288],
       [ 31.8334842, 119.9741288],
       [ 31.8329528, 119.97385  ],
       [ 31.8325784, 119.97385  ],
       [ 31.8323418, 119.9736456],
       [ 31.8322256, 119.9726404],
       [ 31.832113 , 119.9729526],
       [ 31.832028 , 119.974514 ],
       [ 31.832028 , 119.9743834],
       [ 31.832028 , 119.9741698],
       [ 31.8319616, 119.9744274],
       [ 31.8317896, 119.974509 ],
       [ 31.8317896, 119.9740204],
       [ 31.8314866, 119.9734006],
       [ 31.8314866, 119.9745172],
       [ 31.8340978, 119.9751418],
       [ 31.8338096, 119.975424 ],
       [ 31.840109 , 119.9752844],
       [ 31.840109 , 119.9735744],
       [ 31.840109 , 119.9722138],
       [ 31.840109 , 119.9734124],
       [ 31.840109 , 119.9744798],
       [ 31.840109 , 119.9739296],
       [ 31.840109 , 119.9731904],
       [ 31.840109 , 119.9730126],
       [ 31.840109 , 119.9740198],
       [ 31.840109 , 119.974186 ],
       [ 31.8386634, 119.9745968],
       [ 31.837597 , 119.974783 ],
       [ 31.8350352, 119.9747742],
       [ 31.8350352, 119.975    ],
       [ 31.8350352, 119.975    ],
       [ 31.8343444, 119.975    ],
       [ 31.8335858, 119.9741344],
       [ 31.8329912, 119.9737046],
       [ 31.8326098, 119.9738546],
       [ 31.8330162, 119.97385  ],
       [ 31.8340648, 119.97385  ],
       [ 31.8342278, 119.97385  ],
       [ 31.8336918, 119.973569 ],
       [ 31.8331398, 119.9719008],
       [ 31.8326236, 119.9723982],
       [ 31.833211 , 119.9723982],
       [ 31.833221 , 119.9728326],
       [ 31.8333086, 119.9724118],
       [ 31.8328944, 119.973812 ],
       [ 31.8328944, 119.9741868],
       [ 31.8326272, 119.9753862],
       [ 31.8326272, 119.9728718],
       [ 31.8335674, 119.9721308],
       [ 31.835375 , 119.9721308],
       [ 31.8352362, 119.97233  ],
       [ 31.834975 , 119.97385  ],
       [ 31.8365756, 119.97385  ],
       [ 31.8382742, 119.9706052],
       [ 31.8362644, 119.9703574],
       [ 31.8317178, 119.973582 ],
       [ 31.832029 , 119.9747056],
       [ 31.8353282, 119.9740148],
       [ 31.8369218, 119.9745418],
       [ 31.840109 , 119.9743562],
       [ 31.840109 , 119.9744566],
       [ 31.840109 , 119.9743028],
       [ 31.840109 , 119.9741234],
       [ 31.840109 , 119.9740454],
       [ 31.8401158, 119.9740392],
       [ 31.8401782, 119.9741814],
       [ 31.8401158, 119.973964 ],
       [ 31.8401158, 119.974152 ],
       [ 31.840109 , 119.9741432],
       [ 31.840109 , 119.9728618],
       [ 31.840109 , 119.9734416],
       [ 31.840109 , 119.9728994],
       [ 31.840109 , 119.9733914],
       [ 31.840109 , 119.97399  ],
       [ 31.840109 , 119.9740392],
       [ 31.840109 , 119.9740392],
       [ 31.840109 , 119.97399  ]])

In [48]:
import math
math.pi

3.141592653589793

In [ ]:
aaa / math.pi

In [103]:
np.array(temp_table.iloc[11,1:3])

array(['119.962065', '31.800114'], dtype=object)

In [104]:
from sklearn.neighbors import BallTree # KDTree for finding out nearest neighbors of the reconstructed space
tree = BallTree(aaa / math.pi, leaf_size=2,metric='haversine')              
dist, ind = tree.query(np.array([31.801409999999997,119.958615]).reshape(1,-1)/math.pi, k=2)

In [105]:
print(ind)

[[58 27]]

In [ ]:
sum(ind[0])

In [ ]:
aaa[98]

In [ ]:
119.968248	31.823365000000003