In [1]:
import pandas as pd
import numpy as np

In [2]:
import re
import os
import sys
import glob

In [ ]:
from HTMLParser import HTMLParser
import sys
import re


class HTMLTableParser(HTMLParser):
    def __init__(self, row_delim="\n", cell_delim="\t"):
        HTMLParser.__init__(self)
        self.despace_re = re.compile(r'\s+')
        self.data_interrupt = False
        self.first_row = True
        self.first_cell = True
        self.in_cell = False
        self.row_delim = row_delim
        self.cell_delim = cell_delim

    def handle_starttag(self, tag, attrs):
        self.data_interrupt = True
        if tag == "table":
            self.first_row = True
            self.first_cell = True
        elif tag == "tr":
            if not self.first_row:
                sys.stdout.write(self.row_delim)
            self.first_row = False
            self.first_cell = True
            self.data_interrupt = False
        elif tag == "td" or tag == "th":
            if not self.first_cell:
                sys.stdout.write(self.cell_delim)
            self.first_cell = False
            self.data_interrupt = False
            self.in_cell = True

    def handle_endtag(self, tag):
        self.data_interrupt = True
        if tag == "td" or tag == "th":
            self.in_cell = False

    def handle_data(self, data):
        if self.in_cell:
            #if self.data_interrupt:
            #   sys.stdout.write(" ")
            sys.stdout.write(self.despace_re.sub(' ', data).strip())
            self.data_interrupt = False


parser = HTMLTableParser() 
parser.feed(sys.stdin.read('4新街口西.html', header=0))

In [31]:
data = pd.read_html('4新街口西.html', header=0)

data[0].columns.values.tolist()[0]

'江南公交第二巴士公司 行 车 记 录 表 线路：4路 总站名称：新街口西 2018-12-05 星期三 早班站长 中班站长 晚班站长'

In [26]:
data[0]

,江南公交第二巴士公司 行 车 记 录 表 线路：4路 总站名称：新街口西 2018-12-05 星期三 早班站长 中班站长 晚班站长,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,循次 计划车次 实际车次,循次,计划车次,实际车次,NaN,合计 0 0,合计,0,0,NaN,NaN,NaN,NaN
1,循次,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,计划车次,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,实际车次,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,合计,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,循次,路排,车次,车号,驾驶员,服务,到达时间,实驶时间(分钟),停歇时间（分钟）,调度时间,开出时间,间隔（分钟）,备注
11,NaN,NaN,1,0896,30000600李强胜,4路上行,05:38:43,35,2,05:40:00,05:40:13,首,NaN
12,NaN,NaN,2,0994,30017072殷宝贵,4路上行,05:42:12,31,8,05:50:00,05:50:12,10,NaN
13,NaN,NaN,3,0999,30026669杨振,4路上行,06:05:09,35,1,06:06:08,06:06:20,16,NaN
14,NaN,NaN,4,0996,30019005潘少枫,4路上行,06:06:19,28,5,06:09:09,06:11:34,5,NaN
15,NaN,NaN,5,0902,30000627薛松,4路上行,06:14:46,29,2,06:15:48,06:16:01,5,NaN
16,NaN,NaN,6,0881,30019567黄玉林,4路上行,06:30:25,37,1,06:31:26,06:31:40,15,NaN
17,NaN,0,7,0898,30022203戴锋,4路上行,NaN,0,1,06:34:27,06:36:36,5,年检
18,NaN,NaN,8,0904,30017086杜宽英,4路上行,06:40:50,36,2,06:41:52,06:42:05,6,NaN
19,NaN,NaN,9,0880,30010799史万青,4路上行,06:43:12,33,5,06:48:37,06:48:53,6,包车
20,NaN,NaN,10,0998,30000589张伶,4路上行,06:54:23,38,1,06:55:24,06:55:43,7,NaN
21,NaN,NaN,11,0896,30000600李强胜,4路上行,06:58:23,37,0,06:59:00,06:58:55,3,NaN
22,NaN,NaN,12,0994,30017072殷宝贵,4路上行,07:12:41,39,1,07:13:00,07:13:18,15,NaN
23,NaN,NaN,13,0991,30026189平汉宁,4路上行,07:15:32,48,1,07:16:00,07:16:14,3,NaN
24,NaN,NaN,14,0901,30019210王敏,4路上行,07:20:39,41,2,07:22:00,07:22:20,6,NaN
25,NaN,NaN,15,0997,30020002朱明春,4路上行,07:26:08,41,0,07:28:00,07:26:36,4,NaN
26,NaN,NaN,16,1002,30022923王华,4路上行,07:50:35,59,1,07:51:35,07:51:48,25,路阻【已报】
27,NaN,NaN,17,0999,30026669杨振,4路上行,07:50:38,54,3,07:53:35,07:53:48,2,NaN
28,NaN,NaN,18,0897,30015108杜宽宝,4路上行,07:55:18,55,1,NaN,07:56:07,3,NaN
29,NaN,NaN,19,0996,30019005潘少枫,4路上行,NaN,0,1,07:06:00,08:02:10,6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,NaN,NaN,103,0994,30020123王立国,4路上行,19:11:53,62,1,19:13:00,19:12:29,1,NaN
114,NaN,0,104,1002,30022900杜长林,4路上行,19:20:32,46,1,NaN,19:21:16,9,塌
115,NaN,NaN,105,0881,30018424郑影,4路上行,19:37:05,52,1,19:38:00,19:38:14,17,沿途阻
116,NaN,NaN,106,0998,30019227吴俊,4路上行,19:39:39,45,1,19:40:00,19:40:58,2,NaN
117,NaN,NaN,107,0896,30020122王大胜,4路上行,19:44:55,41,3,19:47:00,19:47:07,7,NaN
118,NaN,NaN,108,0999,30018223张强,4路上行,19:56:18,42,1,19:57:00,19:57:32,10,NaN
119,NaN,NaN,109,0901,30019549刘自刚,4路上行,20:11:53,48,1,20:13:00,20:12:56,15,NaN
120,NaN,NaN,110,0903,30015111戴永祥,4路上行,20:14:28,42,1,20:15:00,20:15:15,3,NaN
121,NaN,NaN,111,0897,30020009高意宝,4路上行,20:22:15,42,0,20:23:00,20:22:36,7,NaN
122,NaN,0,112,0995,30022906束林万,4路上行,20:32:32,44,1,20:33:00,20:33:38,11,调牌
123,NaN,0,113,0902,30000587张志春,4路上行,20:43:08,46,1,20:44:00,20:44:13,11,塌停
124,NaN,NaN,114,0996,30026983孙其恒,4路上行,20:51:21,45,2,20:53:00,20:53:13,9,NaN
125,NaN,NaN,115,0994,30020123王立国,4路上行,NaN,0,2,20:16:00,21:02:38,9,NaN
126,NaN,NaN,116,1002,30022900杜长林,4路上行,21:15:40,49,1,21:16:00,21:16:24,14,沿途阻
127,NaN,NaN,117,0998,30019227吴俊,4路上行,21:18:03,44,1,21:19:00,21:19:13,3,NaN
128,NaN,NaN,118,0881,30018424郑影,4路上行,21:26:32,46,1,21:27:00,21:27:13,8,NaN
129,NaN,NaN,119,0999,30018223张强,4路上行,21:31:11,43,3,21:34:00,21:34:13,7,NaN
130,NaN,NaN,120,0904,30014579刘建东,4路上行,21:47:19,51,1,21:48:00,21:48:39,14,NaN
131,NaN,NaN,121,0901,30019549刘自刚,4路上行,21:57:11,53,1,21:58:00,21:58:13,10,NaN
132,NaN,NaN,122,0897,30020009高意宝,4路上行,22:00:28,46,0,22:01:00,22:00:46,2,NaN
133,NaN,NaN,123,0991,30018696刘伟1,4路上行,22:06:10,41,3,22:08:00,22:09:39,9,NaN
134,NaN,NaN,124,0996,30026983孙其恒,4路上行,22:17:13,37,4,22:19:00,22:21:30,12,NaN
135,NaN,0,125,0908,30010139沈炜,4路上行,22:38:36,44,1,NaN,22:39:30,18,手动添加
136,NaN,NaN,126,0995,30022906束林万,4路上行,22:45:46,37,1,22:46:00,22:46:14,7,NaN
137,NaN,NaN,127,1000,30019227吴俊,4路上行,22:55:06,35,1,22:56:00,22:56:13,10,NaN
138,NaN,NaN,128,0881,30018424郑影,4路上行,23:06:42,38,1,23:07:00,23:07:13,11,NaN
139,NaN,NaN,129,0897,30020009高意宝,4路上行,23:13:08,34,0,NaN,23:13:27,6,NaN
140,NaN,NaN,130,1002,30022900杜长林,4路上行,23:19:38,33,1,23:20:00,23:20:13,7,NaN
141,NaN,NaN,NaN,0899,30019549刘自刚,4路上行,23:23:21,30,1,23:24:00,23:24:13,4,NaN
142,NaN,NaN,NaN,0904,30014579刘建东,4路上行,23:27:13,27,3,23:30:00,23:30:13,6,NaN

In [35]:
depart_time = data[0].iloc[:,10]
depart_time[11:]

11     05:40:13
12     05:50:12
13     06:06:20
14     06:11:34
15     06:16:01
16     06:31:40
17     06:36:36
18     06:42:05
19     06:48:53
20     06:55:43
21     06:58:55
22     07:13:18
23     07:16:14
24     07:22:20
25     07:26:36
26     07:51:48
27     07:53:48
28     07:56:07
29     08:02:10
30     08:02:20
31     08:12:47
32     08:13:04
33     08:23:20
34     08:24:13
35     08:28:51
36     08:41:17
37     08:45:13
38     08:54:09
39     08:57:48
40     09:04:12
         ...
113    19:12:29
114    19:21:16
115    19:38:14
116    19:40:58
117    19:47:07
118    19:57:32
119    20:12:56
120    20:15:15
121    20:22:36
122    20:33:38
123    20:44:13
124    20:53:13
125    21:02:38
126    21:16:24
127    21:19:13
128    21:27:13
129    21:34:13
130    21:48:39
131    21:58:13
132    22:00:46
133    22:09:39
134    22:21:30
135    22:39:30
136    22:46:14
137    22:56:13
138    23:07:13
139    23:13:27
140    23:20:13
141    23:24:13
142    23:30:13
Name: Unnamed: 10, Length: 132, dtype: object

In [36]:
index = pd.DatetimeIndex(depart_time[11:])

In [38]:
index

DatetimeIndex(['2019-02-25 05:40:13', '2019-02-25 05:50:12',
               '2019-02-25 06:06:20', '2019-02-25 06:11:34',
               '2019-02-25 06:16:01', '2019-02-25 06:31:40',
               '2019-02-25 06:36:36', '2019-02-25 06:42:05',
               '2019-02-25 06:48:53', '2019-02-25 06:55:43',
               ...
               '2019-02-25 22:09:39', '2019-02-25 22:21:30',
               '2019-02-25 22:39:30', '2019-02-25 22:46:14',
               '2019-02-25 22:56:13', '2019-02-25 23:07:13',
               '2019-02-25 23:13:27', '2019-02-25 23:20:13',
               '2019-02-25 23:24:13', '2019-02-25 23:30:13'],
              dtype='datetime64[ns]', name='Unnamed: 10', length=132, freq=None)

In [ ]:
data = pd.Series([a for a in range(len(index))], index=index)

In [143]:
file_list = glob.glob(os.getcwd()+"/*.csv")

In [144]:
file_list

['D:\\github_repository\\MyProject\\timetable\\jn\\4新街口西.csv',
 'D:\\github_repository\\MyProject\\timetable\\jn\\5南湾营.csv']

In [101]:
pd.set_option('max_colwidth',2000)
table1 = pd.read_csv('5南湾营.csv',engine='python',skiprows =8,header=None)

In [102]:
table1

                                                                                                              0
0                   1   1    1        9126 30001128                        0          0                05:00:15
1               1        2        0960 30015791                        0          0     05:08:00   05:08:14   7
2       1        3        9047 30022725                        0          0     05:16:00   05:16:04   7    9045
3               1        4        1112 30012962                        0          0     05:23:00   05:24:17   8
4               1        5        9131 30022917                        0          0     05:30:00   05:30:27   6
5               1        6        9119 30016786                        0          0     05:37:00   05:37:02   6
6               1        7        9046 30016125                        0          0     05:44:00   05:44:22   7
7               1        8        9129 30020031                        0          0     05:51:00   05:51:13   6
8               1   16 9          9124 30016284                        0          0                05:58:03   6
9               1        10       9044 30100021                        0          0     06:05:00   06:05:20   7
10              1        11       1111 30015783                        0          0     06:11:00   06:11:13   5
11              1        12       9123 30020057                        0          0     06:17:00   06:17:13   6
12              1        13       0955 30015470                        0          0     06:23:00   06:23:13   6
13   1        14       9132 30018790                        0          0     06:29:00   06:29:19   6    12 14 2
14              1        15       9126 30001128             06:17:56   35         18    06:36:00   06:36:13   6
15              1   3    16       0960 30015791             06:25:52   37         17    06:43:00   06:43:20   7
16      2        17       9045 30022725                        0          0     06:49:00   06:49:13   5    9045
17              2   2    18       9120 30015363                        0          0     06:54:00   06:54:55   5
18              2        19       9117 30013871                        0          0     07:00:00   07:01:32   6
19              2        20       1112 30012962             06:46:08   40         19    07:05:00   07:05:27   3
20              2        21       9118 30010678                        0          0     07:10:00   07:10:17   4
21              2        22       9130 30014405                        0          0     07:15:00   07:16:30   6
22              2        23       9131 30022917             06:48:25   39         31    07:20:00   07:20:13   3
23              2        24       0957 30019224                        0          0     07:25:00   07:25:31   5
24              2        25       9119 30016786             06:51:13   37         38    07:29:00   07:29:31   4
25              2        26       9128 30002856                        0          0     07:35:00   07:35:36   6
26              2        27       0959 30013885                        0          0     07:41:00   07:43:33   7
27              2        28       9046 30016125             07:10:17   42         34    07:44:00   07:44:43   1
28      2        29       9121 30020031                        0          0     07:48:00   07:48:13   3    9129
29      2        30       0956 30026673                        0          0     07:52:00   07:52:13   4    0958
..                                                                                                          ...
117                                    6   118 0959 30026492     16:45:07   50   29    17:14:00   17:14:59   11
118                                     6   119 9128 30017761     16:47:04   62   36    17:22:00   17:23:47   8
119                            6   120 9047 30019581     16:44:40   50   45    17:30:00   17:30:13   6    25 25
120                                    7   121 9121 30026979     16:41:15   9    61    17:42:00   17:43:05   12
121                                    7   122 9124 30017207     17:17:22   63   36    17:54:00   17:54:16   11
122                                    7   123 9132 30001081     17:30:25   63   37    18:06:00   18:08:21   14
123                                     7   124 0954 30026637     17:56:41   74   21    18:18:00   18:18:13   9
124                                    7   125 9130 30227417     17:53:53   69   37    18:30:00   18:30:59   12
125                                    7   126 9131 30022897     18:30:51   81   16    18:46:00   18:47:37   16
126                                     7   127 1112 30018473     18:21:46   80   34    18:56:00   18:56:13   8
127                                    7   128 9120 30001018     18:46:51   81   20    19:07:00   19:07:13   11
128                                    7   129 0957 30026750     18:52:08   75   28    19:20:00   19:20:13   13
129                                    7   130 9118 30017915     18:47:08   79   45    19:32:00   19:32:15   12
130                                    7   131 0956 30026677     19:10:49   81   33    19:44:00   19:44:13   11
131                                    7   132 0960              19:21:49   70   34    19:56:00   19:56:18   12
132                                                                                                    30026638
133                   7   133 9047 30019581     19:58:53   68   7     20:06:00   20:06:13   9    21 13 2 3 13 6
134                                    8   134 9126 30020020     17:32:34   65   165   20:17:00   20:17:45   11
135                                    8   135 9132 30001081     20:13:54   57   14    20:28:00   20:28:21   10
136                                    8   136 9130 30227417     20:30:11   4    9     20:39:00   20:39:40   11
137                                    8   137 0959 30026492     20:06:37   1    44    20:50:00   20:50:57   11
138                                     8   138 9120 30001018     20:50:17   50   9     21:00:00   21:00:13   9
139                                    8   139 1112 30018473     20:47:38   57   22    21:10:00   21:10:13   10
140                                    8   140 9131 30022897     20:48:01   61   32    21:20:00   21:20:36   10
141                                    8   141 9128 30017761     20:17:03   7    77    21:34:00   21:34:33   13
142                                    8   142 0956 30026677     21:36:13   4    10    21:46:00   21:46:13   11
143                                    8   143 9047 30019581     21:47:45   5    10    21:58:00   21:58:13   12
144                                    8   144 0960 30026638     21:50:43   5    18    22:09:00   22:09:12   10
145
8   145 9124 30017207         20:28:06   4    112   22:20:00   22:20:14   11   15 12 1 3 2
146                                8   146 0871 30000044   164   17:46:01   44   329              23:15:52   55

[147 rows x 1 columns]

In [131]:
table2 = []
for each_one in table1[0]:
    a = str(each_one)[-15:]
    b = re.compile(r'\d+:\d+:\d+').findall(a)
    if len(b) > 0:
        table2.append(b[-1])
#     if len(b) >0:
#         c = re.compile(r'\d+:\d+:\d+').findall(b[0])
#     print(c)

In [132]:
index = pd.DatetimeIndex(table2)

In [139]:
data = pd.Series([a for a in range(len(index))], index=index)

In [142]:
len(data['2019-02-25 07:00:00':'2019-02-25 09:00:00'])

18

In [61]:
for each_one in file_list:
    a = re.compile('\d+\w+')
    b = a.findall(each_one)
    c = re.compile('\d+').findall(b[0])
    d = re.compile('\D+').findall(b[0])

In [42]:
import datetime
datetime.datetime.today().strftime('%Y-%m-%d')+' 07:00:00'

'2019-02-26 07:00:00'

In [ ]:
def main():
    file_list = glob.glob(os.getcwd()+"/*.txt")
    for each_one in file_list:
        txt_file = open(each_one, encoding="utf-8")
        a = txt_file.read()
        a = a.replace('\n', '')
        out_file = open('1_'+os.path.basename(txt_file.name),
                        'w', encoding='utf-8')
        out_file.write(re.sub(r'(?<=[.])(?=[^\s])', r'\n', a))
        out_file.close()
        txt_file.close()


if __name__ == "__main__":
    main()

In [ ]:
pd = pd.read_csv()